version: '3'
services:
  kafka:
    image: spotify/kafka
# exemplo de cluster: https://github.com/zoidbergwill/docker-compose-kafka/blob/master/docker-compose.yml
    container_name: kafka
    network_mode: "host"
    ports:
      - 9092:9092
      - 2181:2181
      # https://kafka.apache.org/quickstart
      # >cat opt/kafka_2.11-0.10.1.0/config/server.properties | grep broker.id
      # broker.id=0
      # >cat opt/kafka_2.11-0.10.1.0/config/server.properties | grep listeners=
      # #listeners=PLAINTEXT://:9092
      # #advertised.listeners=PLAINTEXT://your.host.name:9092
      # >cat opt/kafka_2.11-0.10.1.0/config/server.properties | grep log.dirs
      # log.dirs=/tmp/kafka-logs
      #          ./opt/kafka_2.11-0.10.1.0
    command:
        - bash
        - -c
        - |
          sed -i 's|broker.id=.*|broker.id=1|' /opt/kafka_2.11-0.10.1.0/config/server.properties
          sed -i 's|#listeners=PLAINTEXT.*|listeners=PLAINTEXT://:9093|' /opt/kafka_2.11-0.10.1.0/config/server.properties
          /bin/kafka-server-start.sh /opt/kafka_2.11-0.10.1.0/config/server.properties &
    environment:
      - "ADVERTISED_HOST=0.0.0.0"
      #- "ADV_HOST=0.0.0.0"
      - "ADVERTISED_PORT=9092"
    #networks:
    #  - kafka_net

  producer:
    image: tonanuvem/producer_kafka:latest
    container_name: producer
    network_mode: "host"
    ports:
      - 80:5001
      - 5001:5001
    restart: on-failure
    environment:
      - "HOST=0.0.0.0"
      #- "HOST=kafka"
      - "PORTA=9092"
      - "TOPICO=meu-topico"
      - "SLACK=inserir-webhook"
      - "CANAL=lab-produtor"
    #networks:
    #  - kafka_net
    depends_on:
      - kafka
    #links:
    #  - kafka
    #healthcheck:
    #    test: ["CMD", "nc", "-z", "http://0.0.0.0:9092"]
    #    interval: 30s
    #    timeout: 10s
    #    retries: 5
    # command: /bin/sh -c 'sleep 10'
    # command: /bin/sh -c "for i in {1..100} ; do if ! nc -z 0.0.0.0:9092 > /dev/null ; then echo waiting on kafka for $i seconds; sleep $i; fi; done; echo Connected!;"
    #command: >
    #  /bin/sh -c "
    #    echo Waiting for kafka service start...;
    #    while ! nc -z 0.0.0.0 9092;
    #    do
    #      sleep 1;
    #    done;
    #    echo Connected!;
    #  "

  consumer:
    image: tonanuvem/consumer_kafka:latest
    container_name: consumer
    network_mode: "host"
    restart: on-failure
    environment:
      - "HOST=0.0.0.0"
      #- "HOST=kafka"
      - "PORTA=9092"
      - "TOPICO=meu-topico"
      - "SLACK=inserir-webhook"
      - "CANAL=lab-consumidor"
    #networks:
    #  - kafka_net
    depends_on:
      - kafka
      - producer
    # command: /bin/sh -c 'sleep 15s'

  kafkamanager:
    image: kafkamanager/kafka-manager
    container_name: kafkamanager
    network_mode: "host"
    restart: on-failure
    environment:
      #- "ZK_HOSTS=kafka"
      - "ZK_HOSTS=0.0.0.0"
    #networks:
    #  - kafka_net
    depends_on:
      - kafka

#networks:
#  kafka_net:
