version: '3'
services:
  kafka:
    image: spotify/kafka
    container_name: kafka
    network_mode: "host"
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      - "ADVERTISED_HOST=0.0.0.0"
      #- "ADV_HOST=0.0.0.0"
      - "ADVERTISED_PORT=9092"
    #networks:
    #  - kafka_net

  producer:
    image: tonanuvem/producer_kafka:latest
    container_name: producer
    network_mode: "host"
    ports:
      - 80:5001
      - 5001:5001
    restart: on-failure
    environment:
      - "HOST=0.0.0.0"
      #- "HOST=kafka"
      - "PORTA=9092"
      - "TOPICO=meu-topico"
      - "SLACK=inserir-webhook"
      - "CANAL=lab-consumidor"
    #networks:
    #  - kafka_net
    depends_on:
      - kafka
    #links:
    #  - kafka
    #healthcheck:
    #    test: ["CMD", "nc", "-z", "http://0.0.0.0:9092"]
    #    interval: 30s
    #    timeout: 10s
    #    retries: 5
    # command: /bin/sh -c 'sleep 10'
    # command: /bin/sh -c "for i in {1..100} ; do if ! nc -z 0.0.0.0:9092 > /dev/null ; then echo waiting on kafka for $i seconds; sleep $i; fi; done; echo Connected!;"
    #command: >
    #  /bin/sh -c "
    #    echo Waiting for kafka service start...;
    #    while ! nc -z 0.0.0.0 9092;
    #    do
    #      sleep 1;
    #    done;
    #    echo Connected!;
    #  "

  consumer:
    image: tonanuvem/consumer_kafka:latest
    container_name: consumer
    network_mode: "host"
    restart: on-failure
    environment:
      #- "HOST=0.0.0.0"
      - "HOST=kafka"
      - "PORTA=9092"
      - "TOPICO=meu-topico"
      - "SLACK=inserir-webhook"
      - "CANAL=lab-consumidor"
    #networks:
    #  - kafka_net
    depends_on:
      - kafka
      - producer
    # command: /bin/sh -c 'sleep 15s'
      
#networks:
#  kafka_net:
